class VSM_Version
{
    string                                  m_WarningMessage = "Não edite este arquivo! | Do not edit this file!";
    
    [NonSerialized()]
    static ref VSM_Version                  m_Instance;
    [NonSerialized()]
    bool                                    m_IsNew;
    [NonSerialized()]
    int                                     m_LastModuleVersion; // usado para indicar a ultima versão carregada, pois vai ser migrada aqui e preciso dela em outros lugares

    int                                     m_ModuleVersion;
    ref map<string, ref VSM_VersionAddon>   m_Addons;

    void VSM_Version()
    {
        CheckPaths();

        if (FileExist(VSM_Constants.SETTING_FILE))
            LoadConfig();
        else
            OnDefaults();

        CheckMigration();
    }

    void CheckPaths()
    {
        if (!FileExist(VSM_Constants.ITZ_PROFILE_FOLDER_NAME))
            MakeDirectory(VSM_Constants.ITZ_PROFILE_FOLDER_NAME);
        
        if (!FileExist(VSM_Constants.GENERAL_PATH))
            MakeDirectory(VSM_Constants.GENERAL_PATH);

        if (!FileExist(VSM_Constants.VERSION_FILE))
            m_IsNew = true;
    }

    void LoadConfig()
    {
        JsonFileLoader<VSM_Version>.JsonLoadFile(VSM_Constants.VERSION_FILE, this);
    }

    void SaveConfig()
    {
        JsonFileLoader<VSM_Version>.JsonSaveFile(VSM_Constants.VERSION_FILE, this);
    }

    void OnDefaults()
    {
        Print("[ITZ][VSM] Nenhum arquivo de versão encontrado, criando arquivo de versão com valores padrão.");

        m_ModuleVersion = VSM_ModuleVersion.V_0000;
        m_LastModuleVersion = m_ModuleVersion;

        m_Addons = new map<string, ref VSM_VersionAddon>;

        SaveConfig();
    }

    void CheckMigration()
    {
        if(m_ModuleVersion == VSM_ModuleVersion.CURRENT_VERSION)  return;

        Print("[ITZ][VSM] Migrando versão de: " + m_ModuleVersion.ToString() + " para: " + VSM_ModuleVersion.CURRENT_VERSION.ToString());

        //TODO: implementar migrações aqui

        m_ModuleVersion = VSM_ModuleVersion.CURRENT_VERSION;
        SaveConfig();
    }

    void RegisterAddon(VSM_VersionAddon addon)
    {
        if (!m_Addons)
            m_Addons = new map<string, ref VSM_VersionAddon>;

        if (m_Addons.Contains(addon.m_Id))
        {
            Print("[ITZ][VSM] Addon " + addon.m_Id + " já registrado, ignorando...");
            return;
        }

        m_Addons.Insert(addon.m_Id, addon);
        SaveConfig();
    }

    bool HasAddon(string id)
    {
        if (!m_Addons) return false;
        return m_Addons.Contains(id);
    }

    VSM_VersionAddon GetAddon(string id)
    {
        if (!m_Addons) return null;
        return m_Addons.Get(id);
    }

    static VSM_Version GetManager()
    {
        if (!m_Instance)
        {
            m_Instance = new VSM_Version();
        }
            
        return m_Instance;
    }
}

class VSM_VersionAddon
{
    string m_Id;
    int m_Version;
    string m_Description;
}